services:
  erp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  static-server:
    build:
      context: ./static-server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"


